import { fail, redirect } from '@sveltejs/kit';
import type { Actions, PageServerLoad } from './$types';
import { parseTournamentForm } from '../shared';

export const load: PageServerLoad = () => {
	return {
		title: 'New tournament · EMGC Bet',
		description: 'Create a new EMGC Bet tournament.'
	};
};

export const actions: Actions = {
	default: async ({ request, locals: { supabase } }) => {
		const formData = await request.formData();
		const { data, errors } = parseTournamentForm(formData);
		if (!data) {
			return fail(400, { errors, values: Object.fromEntries(formData) });
		}

		// slug isn't part of `data` (parseTournamentForm never asks for one — it's
		// auto-generated by an insert-only DB trigger, same slugify()-if-omitted
		// pattern as players), so it has to come back from the insert itself to
		// redirect to the tournament just created rather than the list.
		const { data: inserted, error: insertError } = await supabase
			.from('tournaments')
			.insert(data)
			.select('slug')
			.single();
		if (insertError) {
			return fail(400, {
				errors: { form: insertError.message },
				values: Object.fromEntries(formData)
			});
		}

		redirect(303, `/admin/tournaments/${inserted.slug}`);
	}
};
