-- Powers /admin/audit's live-tail toggle. Same pattern as
-- 20260723000003_create_players.sql/20260723000004_create_bids.sql/
-- 20260723000005_create_live_lots.sql — a table needs to be explicitly
-- added to this publication before Realtime broadcasts anything for it at
-- all, regardless of how correct a subscribing client's code is.
--
-- audit_events' existing RLS (Admin/Owner-only SELECT, no other policy —
-- see 20260723000007_create_audit_events.sql) applies to Realtime
-- subscribers the same way it applies to a plain REST read: a
-- non-Admin/Owner subscriber's channel receives nothing for this table,
-- not an error, matching how their own SELECT already resolves to zero
-- rows today.
alter publication supabase_realtime add table public.audit_events;
