-- Phase 7 (set-placement task): resolves an explicit open question the
-- backlog flagged rather than leaving implicit — confirmed with the user
-- rather than assumed, since golf ties for a placement are real (e.g. two
-- players tied for 3rd) and spec 4.8 never says whether Player.placement
-- allows duplicates per tournament. Decision: disallow ties entirely — an
-- Admin resolves a tie some other way (e.g. a scorecard playoff) before
-- entering results, rather than the app splitting a placement's pot share
-- across multiple players.
--
-- A plain unique index, not a partial one restricted to "where placement
-- is not null": Postgres unique indexes already treat NULL as distinct
-- from every other NULL, so any number of not-yet-placed players (the
-- common case, before results are entered) coexist fine without an
-- explicit NULL exclusion.
--
-- This is enforced at the DB level as defense-in-depth alongside the
-- set-placement Edge Function's own check — same "validate in the
-- function, constrain in the schema too" belt-and-suspenders pattern
-- already used elsewhere (e.g. live_lots' queue_position, payouts'
-- unique(player_id)).
create unique index players_tournament_id_placement_key
  on public.players (tournament_id, placement);
